# Generated by Django 4.1.3 on 2023-01-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('lougradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('setor', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('doses', models.IntegerField()),
                ('periodicidade', models.IntegerField()),
                ('intervalo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('situacao', models.CharField(max_length=10)),
                ('data_situacao', models.DateField(null=True, blank=True)),
                ('observacoes', models.CharField(default='', max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacina')),
            ],
        ),
    ]
