# Generated by Django 4.1.3 on 2022-11-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nasc', models.DateField()),
                ('cargo_pretendido', models.CharField(max_length=25)),
                ('texto_curriculo', models.TextField()),
            ],
        ),
    ]
